### ISSUE TITLE
Reading the ROS2 stored data with APIs(Python)

### ISSUE THREAD

**Issue by sushantdhamnekar** [aws-deepracer/aws-deepracer-camera-pkg#4]
I am using this package to create the images and video stream node on the DeepRacer. I am recording the topics with ros2 record command and topics are being stored in a folder with meta data and sql format data. I would like to push this data to Amazon S3 and process it further. There are no python APIs to process this data. How are you processing the stored information? Thank you.

**Comment by pratik-nichat** [comment]
Hello @sushantdhamnekar ,
There is currently no connection between the DeepRacer device and AWS cloud services (S3 etc.) and the images we capture are processed locally on the device as part of the DeepRacer Core application - https://github.com/aws-deepracer/aws-deepracer-launcher .

**Comment by lingjiekong** [comment]
close issue with no more update.
